version: '3.7'

services:
   asynch-request-creator:
      hostname: asynch-request-creator
      image: "vic/asynch-request-creator:0.0.1"
      ports:
          - "8010:8010"
          - "127.0.0.1:8010:8010"
      network:
         - mynet

   asynch-request-reader:
     hostname: asynch-request-reader
     image: "vic/asynch-request-reader:0.0.1"
     ports:
          - "8020:8020"
     network:
         - mynet


   rabbitmq-spring-boot:
     hostname: rabbitmq-spring-boot
     image: "rabbitmq-spring-boot:0.0.1"
     ports:
         - "5672:5672"
         - "15672:15672"
     network:
         - mynet

   mysql-server:
     hostname: mysql-server
     image: "mysql-cucumber:0.0.1"
     restart: always
     environment:
          - MYSQL_ROOT_PASSWORD=devpassword
     ports:
          - "3306:3306"
     network:
         - mynet

networks:
  mynet:
    external: true